name: gitgud-test

services:
  postgres:
    image: postgres:17-alpine
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gitgud_test
    ports:
      - host_ip: 127.0.0.1
        published: 5433
        target: 5432
        protocol: tcp
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d gitgud_test']
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 15s
      start_interval: 1s

networks:
  test-database:
    external: false
    driver: bridge
    name: 'test-database'
    internal: false
