services:
  # Define ports, restart policies, networks
  # in dev and prod compose files

  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
