name: gitgud

services:
  postgres:
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - host_ip: 127.0.0.1
        published: 5432
        target: 5432
        protocol: tcp
    networks:
      - dev-database
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 15s
      start_interval: 1s

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.91.0
    restart: always
    environment:
      ZO_HTTP_PORT: '5080'
      ZO_ROOT_USER_EMAIL: 'admin@example.com'
      ZO_ROOT_USER_PASSWORD: 'AdminPassword1!'
    volumes:
      - openobserve-data:/data
    ports:
      - host_ip: 127.0.0.1
        published: 5080
        target: 5080
        protocol: tcp

networks:
  dev-database:
    external: false
    driver: bridge
    name: 'dev-database'
    internal: false
